# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI Actions

on:
  push:
    branches: ['**']
    tags-ignore: ['*']
  pull_request:

permissions: read-all

env:
  nodeVersion: 20

# Cancel in progress workflows on pull_requests. A Doppler Service Token provides read-only
# access to a single config and is recommended due to its limited access scope.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-build:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run actions/setup-sdk@local
        uses: ./.github/setup-sdk
        with:
          nodeVersion: ${{ env.nodeVersion }}

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Build frontend app
        run: |
          pnpm install && pnpm build
